## VPC
variable "aws_region" {}
variable "region" {}
variable "name_prefix" {}
variable "environment" {}
variable "vpc_cidr" {}
variable "vpc_cidr_blocks" {}
variable "public_subnet_cidrs" {}
variable "private_subnet_cidrs" {}
variable "azs" {}
## EKS
variable "vpc_id" {}
variable "private_subnet_ids" {}
variable "cluster_name" {}
variable "instance_types" {}
variable "ami_type" {}
variable "capacity_type" {}
variable "desired_capacity" {}
variable "min_size" {}
variable "min_size" {}
# ## Security
variable "oidc_provider_arn" {}
variable "oidc_provider_url" {}
variable "k8s_namespace" {}
variable "k8s_serviceaccount" {}
variable "irsa_service_account" {}
variable "irsa_policy_arn" {}
variable "oidc_thumbprint" {}
variable "irsa_namespace" {}
